CREATE TABLE IF NOT EXISTS toc_servers (
    id VARCHAR(255) PRIMARY KEY,
    uuid VARCHAR(255),
    hostname VARCHAR(255),
    ip_lan VARCHAR(45),
    ip_wan VARCHAR(45),
    ip_ipmi VARCHAR(45),
    az VARCHAR(50),
    cluster VARCHAR(255),
    country VARCHAR(50),
    hall VARCHAR(100),
    idc VARCHAR(100),
    is_disabled BOOLEAN DEFAULT FALSE,
    name VARCHAR(100),
    network_zone VARCHAR(100),
    oid VARCHAR(255),
    os VARCHAR(100),
    os_image VARCHAR(255),
    pod VARCHAR(100),
    rack VARCHAR(100),
    resource_type VARCHAR(100),
    resource_zone_key VARCHAR(255),
    segment VARCHAR(100),
    segment_key VARCHAR(255),
    server_config TEXT,
    server_type VARCHAR(100),
    service_tag VARCHAR(255),
    toc_cluster VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_hostname (hostname),
    INDEX idx_ip_lan (ip_lan),
    INDEX idx_ip_wan (ip_wan),
    INDEX idx_cluster (cluster),
    INDEX idx_az (az),
    INDEX idx_country (country),
    INDEX idx_idc (idc),
    INDEX idx_rack (rack),
    INDEX idx_pod (pod)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 